# Generated by Django 2.1.1 on 2018-09-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('all_day', models.BooleanField()),
                ('date', models.DateTimeField(blank=True)),
                ('open', models.DateTimeField(blank=True)),
                ('close', models.DateTimeField(blank=True)),
            ],
        ),
    ]
