# Generated by Django 2.1.1 on 2018-09-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_auto_20180907_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='close',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='open',
            new_name='start',
        ),
    ]
