# Generated by Django 2.1.1 on 2018-09-09 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_auto_20180908_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
