# Generated by Django 2.1.1 on 2018-09-09 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_auto_20180908_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
