# Generated by Django 2.1.1 on 2018-09-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_auto_20180908_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='in_name_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
