# Generated by Django 2.1.2 on 2019-09-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_event_in_name_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
