# Generated by Django 2.2.4 on 2019-09-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_event_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=True),
        ),
    ]
