# Generated by Django 2.2.4 on 2019-09-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_auto_20190926_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtime',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='gyms.Event'),
        ),
    ]
