# Generated by Django 2.2.4 on 2019-09-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0011_auto_20190926_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
    ]
