# Generated by Django 2.2.4 on 2019-09-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0012_remove_event_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
