# Generated by Django 2.2.4 on 2019-09-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0015_remove_event_closing_soon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closing_soon',
            field=models.BooleanField(default=False),
        ),
    ]
