# Generated by Django 2.2.4 on 2019-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0016_event_closing_soon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='closing_soon',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
