# Generated by Django 2.2.4 on 2019-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0017_auto_20190926_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='open_now',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
