# Generated by Django 2.2.4 on 2019-09-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0018_auto_20190926_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtime',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Event'),
        ),
    ]
